-- Chatify core schema. Apply with: supabase db push
create extension if not exists pgcrypto;
create type public.conversation_kind as enum ('direct','group');
create type public.member_role as enum ('member','admin','owner');
create type public.message_kind as enum ('text','image','video','document','voice','system');
create type public.call_kind as enum ('voice','video');
create type public.call_status as enum ('ringing','active','ended','rejected','missed','busy');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text unique not null check (username ~ '^[a-zA-Z0-9_]{3,32}$'), display_name text not null, avatar_path text, bio text default '', last_seen_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.conversations (id uuid primary key default gen_random_uuid(), kind public.conversation_kind not null, title text, description text default '', avatar_path text, created_by uuid not null references public.profiles(id), pinned_at timestamptz, last_message_at timestamptz, created_at timestamptz not null default now(), deleted_at timestamptz, check ((kind = 'group') or title is null));
create table public.conversation_members (conversation_id uuid references public.conversations(id) on delete cascade, user_id uuid references public.profiles(id) on delete cascade, role public.member_role not null default 'member', joined_at timestamptz not null default now(), left_at timestamptz, muted_until timestamptz, archived_at timestamptz, last_read_message_id uuid, primary key(conversation_id,user_id));
create table public.messages (id uuid primary key default gen_random_uuid(), client_id uuid not null, conversation_id uuid not null references public.conversations(id) on delete cascade, sender_id uuid not null references public.profiles(id), kind public.message_kind not null default 'text', body text, reply_to_id uuid references public.messages(id) on delete set null, edited_at timestamptz, deleted_at timestamptz, created_at timestamptz not null default now(), unique(sender_id,client_id));
alter table public.conversation_members add constraint member_read_message_fk foreign key (last_read_message_id) references public.messages(id) on delete set null;
create table public.message_attachments (id uuid primary key default gen_random_uuid(), message_id uuid not null references public.messages(id) on delete cascade, bucket text not null check(bucket in ('chat-media','voice-messages','documents')), path text not null, mime_type text, size_bytes bigint, duration_ms integer, width integer, height integer, unique(bucket,path));
create table public.message_reactions (message_id uuid references public.messages(id) on delete cascade, user_id uuid references public.profiles(id) on delete cascade, emoji text not null, created_at timestamptz not null default now(), primary key(message_id,user_id,emoji));
create table public.device_tokens (user_id uuid references public.profiles(id) on delete cascade, token text primary key, platform text not null, updated_at timestamptz not null default now());
create table public.calls (id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.conversations(id), initiator_id uuid not null references public.profiles(id), kind public.call_kind not null, status public.call_status not null default 'ringing', started_at timestamptz not null default now(), ended_at timestamptz, signaling jsonb not null default '{}'::jsonb);
create table public.call_participants (call_id uuid references public.calls(id) on delete cascade, user_id uuid references public.profiles(id), joined_at timestamptz, left_at timestamptz, primary key(call_id,user_id));
create index messages_conversation_created_idx on public.messages(conversation_id, created_at desc) where deleted_at is null;
create index members_user_idx on public.conversation_members(user_id) where left_at is null;
create index conversations_last_message_idx on public.conversations(last_message_at desc);
alter table public.profiles enable row level security; alter table public.conversations enable row level security; alter table public.conversation_members enable row level security; alter table public.messages enable row level security; alter table public.message_attachments enable row level security; alter table public.message_reactions enable row level security; alter table public.device_tokens enable row level security; alter table public.calls enable row level security; alter table public.call_participants enable row level security;
create function public.is_member(cid uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from conversation_members where conversation_id=cid and user_id=auth.uid() and left_at is null)$$;
create policy "profiles readable" on public.profiles for select to authenticated using(true); create policy "profile update self" on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy "members read conversations" on public.conversations for select to authenticated using(is_member(id)); create policy "members read memberships" on public.conversation_members for select to authenticated using(is_member(conversation_id));
create policy "members read messages" on public.messages for select to authenticated using(is_member(conversation_id)); create policy "members send messages" on public.messages for insert to authenticated with check(sender_id=auth.uid() and is_member(conversation_id)); create policy "senders update messages" on public.messages for update to authenticated using(sender_id=auth.uid() and is_member(conversation_id));
create policy "members read attachments" on public.message_attachments for select to authenticated using(exists(select 1 from messages m where m.id=message_id and is_member(m.conversation_id))); create policy "members read reactions" on public.message_reactions for select to authenticated using(exists(select 1 from messages m where m.id=message_id and is_member(m.conversation_id))); create policy "self reactions" on public.message_reactions for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "self tokens" on public.device_tokens for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy "members read calls" on public.calls for select to authenticated using(is_member(conversation_id)); create policy "members read call participants" on public.call_participants for select to authenticated using(exists(select 1 from calls c where c.id=call_id and is_member(c.conversation_id)));
-- Private object access: first path component is conversation UUID.
create policy "members read private media" on storage.objects for select to authenticated using(bucket_id in ('chat-media','voice-messages','documents') and public.is_member((storage.foldername(name))[1]::uuid));
create policy "members upload private media" on storage.objects for insert to authenticated with check(bucket_id in ('chat-media','voice-messages','documents') and public.is_member((storage.foldername(name))[1]::uuid));
create policy "avatar public read" on storage.objects for select using(bucket_id='avatars'); create policy "avatar self upload" on storage.objects for insert to authenticated with check(bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text);
alter publication supabase_realtime add table public.messages, public.message_reactions, public.conversation_members, public.calls;
